
package pe.bf.ws.simulador;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimuladorPt", targetNamespace = "http://pe.company.com/Simulador")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimuladorPt {


    /**
     * 
     * @param ahorroNuevoProductoPasivoReqParam
     * @return
     *     returns pe.bf.ws.simulador.RespuestaSimulador
     */
    @WebMethod(action = "http://pe.company.com/Simulador/ahorroNuevoProductoPasivoRequest")
    @WebResult(name = "ahorroNuevoProductoPasivoRespParam", targetNamespace = "http://pe.company.com/Simulador/Resp", partName = "ahorroNuevoProductoPasivoRespParam")
    @Action(input = "http://pe.company.com/Simulador/ahorroNuevoProductoPasivoRequest", output = "http://pe.company.com/Simulador/ahorroNuevoProductoPasivoResponse")
    public RespuestaSimulador ahorroNuevoProductoPasivo(
        @WebParam(name = "ahorroNuevoProductoPasivoReqParam", targetNamespace = "http://pe.company.com/Simulador/Req", partName = "ahorroNuevoProductoPasivoReqParam")
        SimulacionDatos ahorroNuevoProductoPasivoReqParam);

}
